# Proyecto/namespace de Harbor donde se publicará la imagen.
export CI_REPO_IMAGE_NAMESPACE="plataformas"

# Nombre funcional de la imagen.
export CI_REPO_IMAGE_NAME="prompt-scanner"

# Tag explícito para esta versión de la imagen.
export CI_REPO_IMAGE_TAG="1.0.0-node22-nvm0.40.3"
